### ISSUE TITLE
Strip out timber from the base wp-install and turn it into a script

### ISSUE THREAD

**Issue by zsturgess** [DesignyourCode/wp-install#5]
Remove the timber starter theme from our composer.json and write a composer script so that people's forks can re-enable it with one command. Compile will need to detect if timber is required and enable the plugin if needed.

**Comment by DesignyourCode** [comment]
Updates have been made to the standard settings for WP Install. I may look into this further, but currently Timber Starter Theme includes the Timber Library plugin as a dependency, but it is an older version. Until that is updated, I want to leave Timber Starter Theme out of WP Install.
