### ISSUE TITLE
Auto theme handling

### ISSUE THREAD

**Issue by zsturgess** [DesignyourCode/wp-install#6]

**Comment by zsturgess** [comment]
If there's only one theme, activate it. If the current theme setup is invalid, activate the first theme. Else, do nothing.

**Comment by DesignyourCode** [comment]
Updates have been made to the default settings.
WP Install no longer uses wp-cli. Instead **twentysixteen** Wordpress theme has been added to get Wordpress up and running immediately, and work as closely a normal install of Wordpress would.
